language: python
python:
  - "3.7"
install: 
  - pip install -r requirements.txt
  - pip install pandas
  - pip install numpy
  - pip install scipy
  - pip install matplotlib
script:
  - python -m salmon.test
